import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { FiArrowRight, FiBookOpen, FiCheckCircle, FiLayers, FiUsers } from 'react-icons/fi'
import api, { messageFrom } from '../services/api.js'
import CourseCard from '../components/CourseCard.jsx'
import Loader from '../components/Loader.jsx'

export default function Home() {
	const [courses, setCourses] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
	useEffect(() => { api.get('/courses/all-courses?limit=3').then(({ data }) => setCourses(data.courses || [])).catch((err) => setError(messageFrom(err))).finally(() => setLoading(false)) }, [])
	return <>
		<section className="hero"><div className="container hero-grid"><div><span className="eyebrow">A better way to build skills</span><h1>Learn with clarity. <span>Build with confidence.</span></h1><p className="hero-copy">NGSkillForge brings focused courses, practical assignments, and a learning path that keeps your momentum moving forward.</p><div className="hero-actions"><Link className="btn btn-primary" to="/courses">Explore courses <FiArrowRight /></Link><Link className="btn btn-secondary" to="/register">Start learning</Link></div></div><div className="hero-art"><div className="art-top"><span>MY LEARNING SPACE</span><span>● LIVE</span></div><div className="art-panel"><small>CONTINUE LEARNING</small><h3>Build your next skill stack</h3><div className="progress"><span /></div><div className="art-stat"><span>Course progress</span><strong>68%</strong></div><div className="art-stat"><span>Next up</span><strong>Practical assignment</strong></div></div></div></div></section>
		<section className="section"><div className="container"><div className="section-heading"><span className="eyebrow">Everything in one place</span><h2>A learning experience that feels considered.</h2><p className="muted">Less hunting. More doing. Every part of the platform is designed around useful progress.</p></div><div className="feature-grid"><Feature icon={<FiBookOpen />} title="Focused courses" text="Clear course content built around the skills you want to use." /><Feature icon={<FiLayers />} title="Practical work" text="Assignments turn new knowledge into something you can apply." /><Feature icon={<FiUsers />} title="Your pace, your path" text="Keep your learning organized with a personal space that follows you." /></div></div></section>
		<section className="section" style={{ background: '#fff' }}><div className="container"><div className="section-heading"><span className="eyebrow">Start somewhere useful</span><h2>Popular courses</h2><p className="muted">A quick look at what is available in the learning catalog.</p></div>{loading ? <Loader label="Loading courses..." /> : error ? <div className="status error">{error}</div> : courses.length ? <div className="course-grid">{courses.map((course) => <CourseCard key={course._id} course={course} />)}</div> : <div className="empty-state">Courses will appear here once they are published.</div>}<div style={{ marginTop: 28 }}><Link className="auth-link" to="/courses">View all courses <FiArrowRight /></Link></div></div></section>
		<section className="section"><div className="container"><div className="section-heading"><span className="eyebrow">A simple rhythm</span><h2>From curious to capable.</h2></div><div className="steps-grid"><div className="step-card"><h3>Choose your direction</h3><p>Browse the catalog and find a course that matches your next goal.</p></div><div className="step-card"><h3>Learn in context</h3><p>Work through structured material that keeps the why close to the how.</p></div><div className="step-card"><h3>Put it to work</h3><p>Complete assignments and build confidence through practice.</p></div></div></div></section>
		<section className="section" style={{ paddingTop: 0 }}><div className="container"><div className="benefit-grid"><div className="benefit-card"><FiCheckCircle /><div><h3>Made for real progress</h3><p>Keep the next step visible and your learning space easy to return to.</p></div></div><div className="benefit-card"><FiCheckCircle /><div><h3>Useful by design</h3><p>Every screen stays focused on discovering, learning, and applying.</p></div></div></div><div className="cta"><div><h2>Make your next hour count.</h2><p>Find a course and start building a skill you can use.</p></div><Link className="btn btn-primary" to="/courses">Browse the catalog <FiArrowRight /></Link></div></div></section>
	</>
}
function Feature({ icon, title, text }) { return <div className="feature-card"><div className="feature-icon">{icon}</div><h3>{title}</h3><p>{text}</p></div> }
