/**
 * Utility for exporting course topic notes into Google Docs / Word compatible format
 * and rich-text clipboard for 1-click paste into Google Docs.
 */

export function generateTopicHtmlDocument(course, topic) {
  const courseTitle = course?.title || 'Course Notes'
  const topicTitle = `Topic ${topic?.order || 1}: ${topic?.title || 'Overview'}`
  const topicDesc = topic?.description || ''
  const lessons = topic?.lessons || []
  const questions = topic?.questions || []
  const tasks = topic?.tasks || []

  let html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${courseTitle} - ${topicTitle}</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #1e293b; max-width: 800px; margin: 40px auto; padding: 0 20px; }
  h1 { color: #0f172a; border-bottom: 2px solid #2563eb; padding-bottom: 8px; font-size: 26px; }
  h2 { color: #1d4ed8; margin-top: 32px; font-size: 20px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
  h3 { color: #0f172a; margin-top: 24px; font-size: 16px; }
  .badge { display: inline-block; background: #eff6ff; color: #2563eb; border: 1px solid #bfdbfe; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; }
  .desc { color: #475569; font-size: 14px; margin-bottom: 24px; }
  pre { background: #0f172a; color: #f8fafc; padding: 14px; border-radius: 6px; overflow-x: auto; font-family: 'Consolas', 'Courier New', monospace; font-size: 13px; }
  code { background: #f1f5f9; color: #0f172a; padding: 2px 5px; border-radius: 3px; font-family: 'Consolas', monospace; font-size: 13px; }
  pre code { background: none; color: inherit; padding: 0; }
  .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 16px; margin: 16px 0; }
  .card-title { font-weight: bold; margin-bottom: 8px; color: #0f172a; }
  .answer-box { background: #eff6ff; border-left: 4px solid #2563eb; padding: 10px 14px; margin-top: 8px; font-size: 13.5px; }
  ul { padding-left: 20px; }
  li { margin-bottom: 6px; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8; text-align: center; }
</style>
</head>
<body>
  <h1>📘 ${courseTitle}</h1>
  <div class="desc">
    <span class="badge">NGSkillForge Study Notes</span>
    <h2 style="border: none; margin: 10px 0 4px; color: #0f172a;">${topicTitle}</h2>
    <p>${topicDesc}</p>
  </div>

  <h2>1. Subtopics &amp; Lessons (${lessons.length})</h2>`

  if (lessons.length === 0) {
    html += `<p><em>No subtopic lessons in this topic yet.</em></p>`
  } else {
    lessons.forEach((l, idx) => {
      html += `
      <div class="card">
        <div class="card-title">1.${idx + 1} ${l.title} ${l.duration ? `<span style="font-size:12px;color:#64748b;font-weight:normal;">(${l.duration})</span>` : ''}</div>
        <p>${(l.content || '').replace(/\n/g, '<br/>')}</p>
        ${l.notes ? `<div style="background:#fffbeb;border:1px solid #fde68a;padding:8px 12px;border-radius:4px;margin-top:10px;"><strong>Key Note:</strong> ${l.notes}</div>` : ''}
      </div>`
    })
  }

  html += `<h2>2. Practice &amp; Interview Questions (${questions.length})</h2>`
  if (questions.length === 0) {
    html += `<p><em>No questions added for this topic yet.</em></p>`
  } else {
    questions.forEach((q, idx) => {
      html += `
      <div class="card">
        <div class="card-title">Q${idx + 1}: ${q.question} <span class="badge">${q.type || 'Interview'}</span></div>
        ${q.code ? `<pre><code>${q.code}</code></pre>` : ''}
        ${q.options && q.options.length ? `<ul>${q.options.map(opt => `<li>${opt}</li>`).join('')}</ul>` : ''}
        <div class="answer-box">
          <strong>Answer:</strong> ${q.answer}
          ${q.explanation ? `<br/><span style="color:#475569;font-size:12.5px;">${q.explanation}</span>` : ''}
        </div>
      </div>`
    })
  }

  html += `<h2>3. Hands-on Tasks &amp; Challenges (${tasks.length})</h2>`
  if (tasks.length === 0) {
    html += `<p><em>No tasks added for this topic yet.</em></p>`
  } else {
    tasks.forEach((t, idx) => {
      html += `
      <div class="card">
        <div class="card-title">Task #${t.taskNumber || idx + 1}: ${t.title} <span class="badge">${t.level || 'Practice'}</span></div>
        <p>${t.description || ''}</p>
        ${t.requirements && t.requirements.length ? `<strong>Requirements:</strong><ul>${t.requirements.map(r => `<li>${r}</li>`).join('')}</ul>` : ''}
        ${t.starterCode ? `<strong>Starter Code:</strong><pre><code>${t.starterCode}</code></pre>` : ''}
        ${t.hints && t.hints.length ? `<div style="margin-top:8px;font-size:12.5px;color:#64748b;"><strong>Hints:</strong> ${t.hints.join(' | ')}</div>` : ''}
      </div>`
    })
  }

  html += `
  <div class="footer">
    Generated by NGSkillForge Learning Platform • Study Notes for Google Docs
  </div>
</body>
</html>`

  return html
}

/**
 * Copies formatted notes to clipboard so user can press Ctrl+V directly into Google Docs
 */
export async function copyTopicNotesToClipboard(course, topic) {
  const html = generateTopicHtmlDocument(course, topic)
  const plainText = `${course?.title || 'Course'} - Topic ${topic?.order || 1}: ${topic?.title || ''}\n\n` +
    `Lessons (${(topic?.lessons || []).length}):\n` +
    (topic?.lessons || []).map((l, i) => `${i + 1}. ${l.title}\n${l.content}\n`).join('\n') +
    `\nQuestions (${(topic?.questions || []).length}):\n` +
    (topic?.questions || []).map((q, i) => `Q${i + 1}: ${q.question}\nAns: ${q.answer}\n`).join('\n') +
    `\nTasks (${(topic?.tasks || []).length}):\n` +
    (topic?.tasks || []).map((t, i) => `Task ${i + 1}: ${t.title}\n${t.description}\n`).join('\n')

  try {
    if (navigator.clipboard && window.ClipboardItem) {
      const blobHtml = new Blob([html], { type: 'text/html' })
      const blobText = new Blob([plainText], { type: 'text/plain' })
      const data = [new ClipboardItem({ 'text/html': blobHtml, 'text/plain': blobText })]
      await navigator.clipboard.write(data)
      return true
    }
    await navigator.clipboard.writeText(plainText)
    return true
  } catch (err) {
    console.warn('Clipboard write error, falling back to text copy', err)
    try {
      await navigator.clipboard.writeText(plainText)
      return true
    } catch (fallbackErr) {
      return false
    }
  }
}

/**
 * Downloads a Google Docs / Word compatible .doc file
 */
export function downloadTopicNotesDocument(course, topic) {
  const html = generateTopicHtmlDocument(course, topic)
  const blob = new Blob(['\ufeff' + html], { type: 'application/msword;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  const fileName = `${(course?.title || 'Course').replace(/[^a-z0-9]+/gi, '_')}_Topic_${topic?.order || 1}_Notes.doc`
  link.href = url
  link.download = fileName
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
